#! /bin/sh -eu
#! -*- coding:utf-8; mode:shell-script; -*-

rootdir=$(dirname $(readlink -f "${0}"))
tagfile="${rootdir}/.b6353339-fae0-4c5f-83bf-66463a3bafc6.tag"
minijava="${rootdir}/stage/src/minijava"

die() {
	echo "run: error: $@" >&2
	exit 1
}

test -f "${tagfile}" || die "Cannot find root directory"
test -x "${minijava}" || die "Cannot find compiler executable"

exec "${minijava}" "$@"
