macro(buildx_enable_diagnostics)
	if(${CMAKE_C_COMPILER_ID} MATCHES "GNU|Clang")
		set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -Wextra -Wconversion -Wsign-conversion -Werror -pedantic")
	endif()
	if(${CMAKE_CXX_COMPILER_ID} MATCHES "GNU|Clang")
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -Wconversion -Wsign-conversion -Werror -pedantic -Woverloaded-virtual -Wnon-virtual-dtor")
	endif()
endmacro(buildx_enable_diagnostics)
