include("debug.cmake")

if(NOT DEFINED PROJECT_NAME)
	message(FATAL_ERROR "Buildx: No project name specified")
endif(NOT DEFINED PROJECT_NAME)

if(NOT PROJECT_VERSION)
	message(WARNING "Buildx: No project version specified")
endif(NOT PROJECT_VERSION)

if(NOT DEFINED PROJECT_SHORTCUT)
	set(PROJECT_SHORTCUT ${PROJECT_NAME})
endif(NOT DEFINED PROJECT_SHORTCUT)

if(NOT DEFINED PROJECT_PREFIX)
	set(PROJECT_PREFIX ${PROJECT_SHORTCUT})
endif(NOT DEFINED PROJECT_PREFIX)

include("print_properties.cmake")
include("src_scanner.cmake")
include("library.cmake")
include("install.cmake")
include("dependencies.cmake")
include("utils.cmake")
include("test.cmake")
include("copy_media.cmake")

macro(buildx_set_default_output_dirs)
	set(EXECUTABLE_OUTPUT_PATH ${PROJECT_BINARY_DIR}/bin)
	set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${PROJECT_BINARY_DIR}/bin)
endmacro(buildx_set_default_output_dirs)

macro(buildx_activate_cpp14)
	include(CheckCXXCompilerFlag)
	CHECK_CXX_COMPILER_FLAG("-std=c++14" COMPILER_SUPPORTS_CXX14)
	CHECK_CXX_COMPILER_FLAG("-std=c++1y" COMPILER_SUPPORTS_CXX1Y)
	if(COMPILER_SUPPORTS_CXX14)
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++14")
	elseif(COMPILER_SUPPORTS_CXX1Y)
		set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++1y")
	else()
		message(STATUS "${CMAKE_CXX_COMPILER} does not support C++14")
	endif()
endmacro(buildx_activate_cpp14)
