#!/bin/sh

die() {
	echo "$@"
	exit 1
}

readonly basedir=$(dirname "$0")
readonly rootdir=$(realpath "$basedir/../..")
readonly githookdir=$(realpath "$rootdir/.git/hooks")
readonly sourcedir=$(realpath "$basedir")
readonly tagfile=$(realpath "$rootdir/.b6353339-fae0-4c5f-83bf-66463a3bafc6.tag")

test -f "${tagfile}" || die "Cannot find root directory ($rootdir)"

echo "repo dir:   $rootdir"
echo "source dir: $sourcedir"
echo "hook dir:   $githookdir"

install_hook() {
    readonly target="$sourcedir/$1.hook"
    readonly link="$githookdir/$1"
    readonly target_out=$(realpath --relative-to="$rootdir" "$target")
    readonly link_out=$(realpath --relative-to="$rootdir" "$link")

    if test -f "$link";
    then
        echo "Hook $1 already installed ($link_out)"
    else
        echo "Install hook $1 (ln $link_out -> $target_out)"
        ln -s -f "$target" "$link"
    fi
}

install_hook "pre-commit"
